package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"explorer-graphql/graph/model"
	"explorer-graphql/internal/loaders"
)

// Block is the resolver for the block field.
func (r *queryResolver) Block(ctx context.Context, height int) (*model.Block, error) {
	return loaders.GetBlock(ctx, height)
}

// Blocks is the resolver for the blocks field.
func (r *queryResolver) Blocks(ctx context.Context, cursor *int, limit int) (*model.BlockPaginated, error) {
	return loaders.GetBlocks(ctx, cursor, limit)
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
