apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kepler.fullname" . }}
  labels:
    app: {{ include "kepler.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kepler.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "kepler.name" . }}
    spec:
      initContainers:
        - name: copy-config
          image: busybox:1.34
          command:
            - sh
            - -c
            - |
                echo "Creating destination directories"
                mkdir -p /writable-config/config
                mkdir -p /writable-config/data

                echo "Copying config from /config to /writable-config/config"
                cp -rL /config/addrbook.json /writable-config/config
                cp -rL /config/app.toml /writable-config/config
                cp -rL /config/client.toml /writable-config/config
                cp -rL /config/config.toml /writable-config/config
                cp -rL /config/genesis.json /writable-config/config
                
                cp -rL /keys/node_key.json /writable-config/config
                cp -rL /keys/priv_validator_key.json /writable-config/config

                echo "Copying data from /data to /writable-config/data"
                cp -rL /config/priv_validator_state.json /writable-config/data

                echo "Contents of /writable-config:"
                ls -lR /writable-config

                # echo "Adding genesis account for alice"
                # /root/appd genesis add-genesis-account alice 100000000000stake
                # /root/appd gentx alice 5000000000stake --chain-id blog
                # /root/appd genesis collect-gentxs
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: writable-config
              mountPath: /writable-config
            - name: secret-volume-keys
              mountPath: /keys
      containers:
        - name: kepler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.ports.api }}
              name: api
            - containerPort: {{ .Values.service.ports.rpc }}
              name: rpc
          command:
            - "/root/keplerd"
          args:
            - "start"
            - "--home"
            - "/root/app_config"
          readinessProbe:
            httpGet:
              path: /status
              port: rpc
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: rpc
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          volumeMounts:
            - name: writable-config
              mountPath: /root/app_config
            - name: secret-volume-keyring
              mountPath: /root/app_config/keyring-test
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "kepler.fullname" . }}-appconfig
        - name: writable-config
          emptyDir: {}
        - name: secret-volume-keyring
          secret:
            secretName: {{ include "kepler.fullname" . }}-keyring-secrets
        - name: secret-volume-keys
          secret:
            secretName: {{ include "kepler.fullname" . }}-keys-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kepler.fullname" . }}-client
  labels:
    app: {{ include "kepler.name" . }}
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kepler.name" . }}
      role: client
  template:
    metadata:
      labels:
        app: {{ include "kepler.name" . }}
        role: client
    spec:
      initContainers:
        - name: copy-client-config
          image: busybox:1.34
          command:
            - sh
            - -c
            - |
                echo "Creating destination directory for client config"
                mkdir -p /writable-config/config
                echo "Copying client config from /config to /writable-config/config"
                cp -rL /config/client.toml /writable-config/config
                echo "Contents of /writable-config/config:"
                ls -l /writable-config/config
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: writable-config
              mountPath: /writable-config
            - name: secret-volume-keys
              mountPath: /keys
      containers:
        - name: client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
            - sleep
          args:
            - "infinity"
          volumeMounts:
            - name: writable-config
              mountPath: /root/app_config
            - name: secret-volume-keyring
              mountPath: /root/app_config/keyring-test
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "kepler.fullname" . }}-appconfig
        - name: writable-config
          emptyDir: {}
        - name: secret-volume-keyring
          secret:
            secretName: {{ include "kepler.fullname" . }}-keyring-secrets
        - name: secret-volume-keys
          secret:
            secretName: {{ include "kepler.fullname" . }}-keys-secrets
