apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kepler.fullname" . }}-secrets
type: Opaque
stringData:
  698be1299697cb38ba514f17277aa826350b30c5.address: |-
    {{- (.Files.Get "app_config/keyring-test/698be1299697cb38ba514f17277aa826350b30c5.address") | trim | nindent 4 }}
  alice.info: |-
    {{- (.Files.Get "app_config/keyring-test/alice.info") | trim | nindent 4 }}
  bob.info: |-
    {{- (.Files.Get "app_config/keyring-test/bob.info") | trim | nindent 4 }}
  791b4d8fe6a06d0ce2c562605ff66291af4181ff.address: |-
    {{- (.Files.Get "app_config/keyring-test/791b4d8fe6a06d0ce2c562605ff66291af4181ff.address") | trim | nindent 4 }}