global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "kepler"
    static_configs:
      # For Linux
      # - targets: ["localhost:1317"]

      # For macOs or Windows
      - targets: ["host.docker.internal:1317"]
    params:
      format: ["prometheus"]
    scrape_interval: 15s