global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "kepler"
    static_configs:
      - targets: ["host.docker.internal:1317"]
    params:
      format: ["prometheus"]

  - job_name: node
    static_configs:
    - targets: ['node_exporter:9100']
