style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/dittonetwork/kepler
options:
  commits:
    filters:
      Type:
        - build
        - chore
        - ci
        - docs
        - feat
        - fix
        - perf
        - refactor
        - revert
        - style
        - test
    dedup: true
  commit_groups:
    title_maps:
      build: Build System
      chore: Chores
      ci: Continuous Integration
      docs: Documentation
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      revert: Reverts
      style: Code Style
      test: Tests
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
      - BREAKING CHANGES 