services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=0.0.0.0:10232'
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    ports:
      - "10232:10232"
    networks:
      - monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:11.5.1
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./grafana/dashboards:/var/dashboards
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_HTTP_PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    network_mode: host
    volumes:
      - '/:/host:ro,rslave'

volumes:
  grafana-storage: {}
  prometheus-storage: {}

networks:
  monitoring:
    driver: bridge
