// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: kepler/executors/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76888d1e779625ec, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76888d1e779625ec, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryExecutorsRequest defines a request to fetch all active executors.
type QueryActiveExecutorsRequest struct {
}

func (m *QueryActiveExecutorsRequest) Reset()         { *m = QueryActiveExecutorsRequest{} }
func (m *QueryActiveExecutorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryActiveExecutorsRequest) ProtoMessage()    {}
func (*QueryActiveExecutorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76888d1e779625ec, []int{2}
}
func (m *QueryActiveExecutorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActiveExecutorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActiveExecutorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActiveExecutorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActiveExecutorsRequest.Merge(m, src)
}
func (m *QueryActiveExecutorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryActiveExecutorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActiveExecutorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActiveExecutorsRequest proto.InternalMessageInfo

type QueryActiveExecutorsResponse struct {
	// executors list of active executors.
	Executors []*Executor `protobuf:"bytes,1,rep,name=executors,proto3" json:"executors,omitempty"`
}

func (m *QueryActiveExecutorsResponse) Reset()         { *m = QueryActiveExecutorsResponse{} }
func (m *QueryActiveExecutorsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryActiveExecutorsResponse) ProtoMessage()    {}
func (*QueryActiveExecutorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76888d1e779625ec, []int{3}
}
func (m *QueryActiveExecutorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryActiveExecutorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryActiveExecutorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryActiveExecutorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryActiveExecutorsResponse.Merge(m, src)
}
func (m *QueryActiveExecutorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryActiveExecutorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryActiveExecutorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryActiveExecutorsResponse proto.InternalMessageInfo

func (m *QueryActiveExecutorsResponse) GetExecutors() []*Executor {
	if m != nil {
		return m.Executors
	}
	return nil
}

// QueryEmergencyExecutorsRequest defines a request to fetch emergency executors.
type QueryEmergencyExecutorsRequest struct {
}

func (m *QueryEmergencyExecutorsRequest) Reset()         { *m = QueryEmergencyExecutorsRequest{} }
func (m *QueryEmergencyExecutorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEmergencyExecutorsRequest) ProtoMessage()    {}
func (*QueryEmergencyExecutorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_76888d1e779625ec, []int{4}
}
func (m *QueryEmergencyExecutorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmergencyExecutorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmergencyExecutorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmergencyExecutorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmergencyExecutorsRequest.Merge(m, src)
}
func (m *QueryEmergencyExecutorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmergencyExecutorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmergencyExecutorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmergencyExecutorsRequest proto.InternalMessageInfo

type QueryEmergencyExecutorsResponse struct {
	// executors list of emergency executors.
	Executors []*Executor `protobuf:"bytes,1,rep,name=executors,proto3" json:"executors,omitempty"`
}

func (m *QueryEmergencyExecutorsResponse) Reset()         { *m = QueryEmergencyExecutorsResponse{} }
func (m *QueryEmergencyExecutorsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEmergencyExecutorsResponse) ProtoMessage()    {}
func (*QueryEmergencyExecutorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_76888d1e779625ec, []int{5}
}
func (m *QueryEmergencyExecutorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEmergencyExecutorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEmergencyExecutorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEmergencyExecutorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEmergencyExecutorsResponse.Merge(m, src)
}
func (m *QueryEmergencyExecutorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEmergencyExecutorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEmergencyExecutorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEmergencyExecutorsResponse proto.InternalMessageInfo

func (m *QueryEmergencyExecutorsResponse) GetExecutors() []*Executor {
	if m != nil {
		return m.Executors
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "kepler.executors.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "kepler.executors.QueryParamsResponse")
	proto.RegisterType((*QueryActiveExecutorsRequest)(nil), "kepler.executors.QueryActiveExecutorsRequest")
	proto.RegisterType((*QueryActiveExecutorsResponse)(nil), "kepler.executors.QueryActiveExecutorsResponse")
	proto.RegisterType((*QueryEmergencyExecutorsRequest)(nil), "kepler.executors.QueryEmergencyExecutorsRequest")
	proto.RegisterType((*QueryEmergencyExecutorsResponse)(nil), "kepler.executors.QueryEmergencyExecutorsResponse")
}

func init() { proto.RegisterFile("kepler/executors/query.proto", fileDescriptor_76888d1e779625ec) }

var fileDescriptor_76888d1e779625ec = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x33, 0x16, 0x17, 0x3a, 0xbd, 0xe8, 0x58, 0x61, 0x89, 0xdb, 0xec, 0x12, 0x2c, 0x96,
	0x42, 0x33, 0xdd, 0xf5, 0x22, 0x78, 0xb2, 0x50, 0x0a, 0x9e, 0x34, 0x27, 0xd1, 0xd3, 0x24, 0x3e,
	0x62, 0x68, 0x33, 0x2f, 0xcd, 0x4c, 0x6a, 0x17, 0xbc, 0x28, 0x7e, 0x00, 0xc1, 0x2f, 0xe1, 0xd1,
	0x8f, 0xd1, 0x63, 0xc1, 0x8b, 0x27, 0x91, 0x5d, 0xc1, 0xaf, 0x21, 0x9d, 0x99, 0x54, 0xdd, 0x6c,
	0x50, 0xf1, 0x12, 0x86, 0xf7, 0xfe, 0xbf, 0xf7, 0x7f, 0xfc, 0x1f, 0xa1, 0x83, 0x43, 0x28, 0x8f,
	0xa0, 0xe2, 0x70, 0x0a, 0x69, 0xad, 0xb1, 0x52, 0xfc, 0xb8, 0x86, 0x6a, 0x1a, 0x95, 0x15, 0x6a,
	0x64, 0xd7, 0x6c, 0x37, 0xba, 0xec, 0xfa, 0xd7, 0x45, 0x91, 0x4b, 0xe4, 0xe6, 0x6b, 0x45, 0xfe,
	0x76, 0x8a, 0xaa, 0x40, 0xc5, 0x13, 0xa1, 0xc0, 0xd2, 0xfc, 0x64, 0x9c, 0x80, 0x16, 0x63, 0x5e,
	0x8a, 0x2c, 0x97, 0x42, 0xe7, 0x28, 0x9d, 0x76, 0x3d, 0xc3, 0x0c, 0xcd, 0x93, 0x5f, 0xbc, 0x5c,
	0x75, 0x90, 0x21, 0x66, 0x47, 0xc0, 0x45, 0x99, 0x73, 0x21, 0x25, 0x6a, 0x83, 0x28, 0xd7, 0x1d,
	0xb6, 0x56, 0x6c, 0x5e, 0x4e, 0xb0, 0xd1, 0x12, 0x94, 0xa2, 0x12, 0x85, 0xe3, 0xc3, 0x75, 0xca,
	0x1e, 0x5f, 0x6c, 0xf5, 0xc8, 0x14, 0x63, 0x38, 0xae, 0x41, 0xe9, 0x30, 0xa6, 0x37, 0x7e, 0xab,
	0xaa, 0x12, 0xa5, 0x02, 0x76, 0x9f, 0xf6, 0x2c, 0xdc, 0x27, 0x23, 0xb2, 0xb5, 0x36, 0xe9, 0x47,
	0x8b, 0x11, 0x44, 0x96, 0xd8, 0x5b, 0x3d, 0xfb, 0x32, 0xf4, 0x3e, 0x7c, 0xff, 0xb8, 0x4d, 0x62,
	0x87, 0x84, 0x1b, 0xf4, 0x96, 0x99, 0xf9, 0x20, 0xd5, 0xf9, 0x09, 0xec, 0x37, 0x44, 0x63, 0xf9,
	0x84, 0x0e, 0x96, 0xb7, 0x9d, 0xf7, 0x3d, 0xba, 0x7a, 0xe9, 0xd2, 0x27, 0xa3, 0x95, 0xad, 0xb5,
	0x89, 0xdf, 0xb6, 0x6f, 0xb8, 0xf8, 0xa7, 0x38, 0x1c, 0xd1, 0xc0, 0x4c, 0xde, 0x2f, 0xa0, 0xca,
	0x40, 0xa6, 0xd3, 0x96, 0xf7, 0x33, 0x3a, 0xec, 0x54, 0xfc, 0xaf, 0xfd, 0xe4, 0xf5, 0x0a, 0xbd,
	0x6a, 0xa6, 0xb3, 0xb7, 0x84, 0xf6, 0x6c, 0x3e, 0xec, 0x76, 0x9b, 0x6d, 0x9f, 0xc1, 0xdf, 0xfc,
	0x83, 0xca, 0xee, 0x16, 0xee, 0xbc, 0xf9, 0xf4, 0xed, 0xfd, 0x95, 0x3b, 0x6c, 0x93, 0x3f, 0xcf,
	0xb5, 0x46, 0x09, 0xfa, 0x25, 0x56, 0x87, 0xbc, 0xe3, 0xf0, 0x4c, 0x51, 0x76, 0x00, 0x7a, 0x21,
	0x67, 0xb6, 0xd3, 0xe1, 0xb5, 0xfc, 0x5c, 0x7e, 0xf4, 0xb7, 0x72, 0x97, 0xdf, 0x2b, 0x7a, 0xf3,
	0x00, 0x74, 0x3b, 0x60, 0xb6, 0xdb, 0x31, 0xa8, 0xf3, 0x5a, 0xfe, 0xf8, 0x1f, 0x08, 0xeb, 0xbe,
	0xf7, 0xf0, 0x6c, 0x16, 0x90, 0xf3, 0x59, 0x40, 0xbe, 0xce, 0x02, 0xf2, 0x6e, 0x1e, 0x78, 0xe7,
	0xf3, 0xc0, 0xfb, 0x3c, 0x0f, 0xbc, 0xa7, 0xbb, 0x59, 0xae, 0x5f, 0xd4, 0x49, 0x94, 0x62, 0xb1,
	0x34, 0xbd, 0xd3, 0x5f, 0xf2, 0xd3, 0xd3, 0x12, 0x54, 0xd2, 0x33, 0x3f, 0xce, 0xdd, 0x1f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xef, 0xaa, 0x01, 0x42, 0x1d, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GetActiveExecutors returns active executors.
	GetActiveExecutors(ctx context.Context, in *QueryActiveExecutorsRequest, opts ...grpc.CallOption) (*QueryActiveExecutorsResponse, error)
	// GetEmergencyExecutors returns a list of emergency executors. They are also active.
	GetEmergencyExecutors(ctx context.Context, in *QueryEmergencyExecutorsRequest, opts ...grpc.CallOption) (*QueryEmergencyExecutorsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/kepler.executors.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetActiveExecutors(ctx context.Context, in *QueryActiveExecutorsRequest, opts ...grpc.CallOption) (*QueryActiveExecutorsResponse, error) {
	out := new(QueryActiveExecutorsResponse)
	err := c.cc.Invoke(ctx, "/kepler.executors.Query/GetActiveExecutors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetEmergencyExecutors(ctx context.Context, in *QueryEmergencyExecutorsRequest, opts ...grpc.CallOption) (*QueryEmergencyExecutorsResponse, error) {
	out := new(QueryEmergencyExecutorsResponse)
	err := c.cc.Invoke(ctx, "/kepler.executors.Query/GetEmergencyExecutors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GetActiveExecutors returns active executors.
	GetActiveExecutors(context.Context, *QueryActiveExecutorsRequest) (*QueryActiveExecutorsResponse, error)
	// GetEmergencyExecutors returns a list of emergency executors. They are also active.
	GetEmergencyExecutors(context.Context, *QueryEmergencyExecutorsRequest) (*QueryEmergencyExecutorsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetActiveExecutors(ctx context.Context, req *QueryActiveExecutorsRequest) (*QueryActiveExecutorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveExecutors not implemented")
}
func (*UnimplementedQueryServer) GetEmergencyExecutors(ctx context.Context, req *QueryEmergencyExecutorsRequest) (*QueryEmergencyExecutorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmergencyExecutors not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kepler.executors.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetActiveExecutors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActiveExecutorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetActiveExecutors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kepler.executors.Query/GetActiveExecutors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetActiveExecutors(ctx, req.(*QueryActiveExecutorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetEmergencyExecutors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEmergencyExecutorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetEmergencyExecutors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kepler.executors.Query/GetEmergencyExecutors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetEmergencyExecutors(ctx, req.(*QueryEmergencyExecutorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kepler.executors.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetActiveExecutors",
			Handler:    _Query_GetActiveExecutors_Handler,
		},
		{
			MethodName: "GetEmergencyExecutors",
			Handler:    _Query_GetEmergencyExecutors_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kepler/executors/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryActiveExecutorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActiveExecutorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActiveExecutorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryActiveExecutorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryActiveExecutorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryActiveExecutorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Executors) > 0 {
		for iNdEx := len(m.Executors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Executors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryEmergencyExecutorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmergencyExecutorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmergencyExecutorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEmergencyExecutorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEmergencyExecutorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEmergencyExecutorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Executors) > 0 {
		for iNdEx := len(m.Executors) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Executors[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryActiveExecutorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryActiveExecutorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Executors) > 0 {
		for _, e := range m.Executors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryEmergencyExecutorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEmergencyExecutorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Executors) > 0 {
		for _, e := range m.Executors {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActiveExecutorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActiveExecutorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActiveExecutorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryActiveExecutorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryActiveExecutorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryActiveExecutorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Executors = append(m.Executors, &Executor{})
			if err := m.Executors[len(m.Executors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmergencyExecutorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmergencyExecutorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmergencyExecutorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEmergencyExecutorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEmergencyExecutorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEmergencyExecutorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Executors = append(m.Executors, &Executor{})
			if err := m.Executors[len(m.Executors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
