// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: kepler/alliance/query.proto

package alliance

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName               = "/kepler.alliance.Query/Params"
	Query_SharedEntropy_FullMethodName        = "/kepler.alliance.Query/SharedEntropy"
	Query_QuorumParams_FullMethodName         = "/kepler.alliance.Query/QuorumParams"
	Query_AlliancesTimeline_FullMethodName    = "/kepler.alliance.Query/AlliancesTimeline"
	Query_AlliancesTimelineAll_FullMethodName = "/kepler.alliance.Query/AlliancesTimelineAll"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a SharedEntropy by index.
	SharedEntropy(ctx context.Context, in *QueryGetSharedEntropyRequest, opts ...grpc.CallOption) (*QueryGetSharedEntropyResponse, error)
	// Queries a QuorumParams by index.
	QuorumParams(ctx context.Context, in *QueryGetQuorumParamsRequest, opts ...grpc.CallOption) (*QueryGetQuorumParamsResponse, error)
	// Queries a list of AlliancesTimeline items.
	AlliancesTimeline(ctx context.Context, in *QueryGetAlliancesTimelineRequest, opts ...grpc.CallOption) (*QueryGetAlliancesTimelineResponse, error)
	AlliancesTimelineAll(ctx context.Context, in *QueryAllAlliancesTimelineRequest, opts ...grpc.CallOption) (*QueryAllAlliancesTimelineResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SharedEntropy(ctx context.Context, in *QueryGetSharedEntropyRequest, opts ...grpc.CallOption) (*QueryGetSharedEntropyResponse, error) {
	out := new(QueryGetSharedEntropyResponse)
	err := c.cc.Invoke(ctx, Query_SharedEntropy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QuorumParams(ctx context.Context, in *QueryGetQuorumParamsRequest, opts ...grpc.CallOption) (*QueryGetQuorumParamsResponse, error) {
	out := new(QueryGetQuorumParamsResponse)
	err := c.cc.Invoke(ctx, Query_QuorumParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AlliancesTimeline(ctx context.Context, in *QueryGetAlliancesTimelineRequest, opts ...grpc.CallOption) (*QueryGetAlliancesTimelineResponse, error) {
	out := new(QueryGetAlliancesTimelineResponse)
	err := c.cc.Invoke(ctx, Query_AlliancesTimeline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AlliancesTimelineAll(ctx context.Context, in *QueryAllAlliancesTimelineRequest, opts ...grpc.CallOption) (*QueryAllAlliancesTimelineResponse, error) {
	out := new(QueryAllAlliancesTimelineResponse)
	err := c.cc.Invoke(ctx, Query_AlliancesTimelineAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a SharedEntropy by index.
	SharedEntropy(context.Context, *QueryGetSharedEntropyRequest) (*QueryGetSharedEntropyResponse, error)
	// Queries a QuorumParams by index.
	QuorumParams(context.Context, *QueryGetQuorumParamsRequest) (*QueryGetQuorumParamsResponse, error)
	// Queries a list of AlliancesTimeline items.
	AlliancesTimeline(context.Context, *QueryGetAlliancesTimelineRequest) (*QueryGetAlliancesTimelineResponse, error)
	AlliancesTimelineAll(context.Context, *QueryAllAlliancesTimelineRequest) (*QueryAllAlliancesTimelineResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) SharedEntropy(context.Context, *QueryGetSharedEntropyRequest) (*QueryGetSharedEntropyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SharedEntropy not implemented")
}
func (UnimplementedQueryServer) QuorumParams(context.Context, *QueryGetQuorumParamsRequest) (*QueryGetQuorumParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuorumParams not implemented")
}
func (UnimplementedQueryServer) AlliancesTimeline(context.Context, *QueryGetAlliancesTimelineRequest) (*QueryGetAlliancesTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlliancesTimeline not implemented")
}
func (UnimplementedQueryServer) AlliancesTimelineAll(context.Context, *QueryAllAlliancesTimelineRequest) (*QueryAllAlliancesTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AlliancesTimelineAll not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SharedEntropy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSharedEntropyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SharedEntropy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SharedEntropy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SharedEntropy(ctx, req.(*QueryGetSharedEntropyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QuorumParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetQuorumParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QuorumParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QuorumParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QuorumParams(ctx, req.(*QueryGetQuorumParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AlliancesTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAlliancesTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AlliancesTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AlliancesTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AlliancesTimeline(ctx, req.(*QueryGetAlliancesTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AlliancesTimelineAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllAlliancesTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AlliancesTimelineAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AlliancesTimelineAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AlliancesTimelineAll(ctx, req.(*QueryAllAlliancesTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kepler.alliance.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "SharedEntropy",
			Handler:    _Query_SharedEntropy_Handler,
		},
		{
			MethodName: "QuorumParams",
			Handler:    _Query_QuorumParams_Handler,
		},
		{
			MethodName: "AlliancesTimeline",
			Handler:    _Query_AlliancesTimeline_Handler,
		},
		{
			MethodName: "AlliancesTimelineAll",
			Handler:    _Query_AlliancesTimelineAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kepler/alliance/query.proto",
}
