name: Check Generated Files

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  check-mock-files:
    name: Check Mock Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.x'
          cache: true

      - name: Check mock files
        run: |
          echo "Running make generate-mocks..."
          make generate-mocks

          echo "Checking for changes in generated files..."
          if [ -n "$(git status --porcelain)" ]; then
            echo "Following files are changed..."
            git status

            echo "Changes:"
            git diff

            exit 1
          else
            echo "No changes detected in generated files."
            exit 0
          fi

  check-proto-files:
    name: Check Proto Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.*'
          cache: true

      - name: Install buf
        if: steps.cache-buf.outputs.cache-hit != 'true'
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.28.1/buf-$(uname -s)-$(uname -m)" -o "/tmp/buf"
          chmod +x "/tmp/buf"
          sudo mv "/tmp/buf" "/usr/local/bin/buf"

      - name: Install Ignite
        if: steps.cache-ignite.outputs.cache-hit != 'true'
        run: |
          mkdir -p $HOME/bin
          curl -sSL "https://get.ignite.com/cli" | OUT_DIR=$HOME/bin bash
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Check proto files
        env:
          DO_NOT_TRACK: 1
        run: |
          echo "Running proto format and generation..."
          # Run proto-format and proto-lint in parallel
          make proto-format & make proto-lint & wait
          # Run proto-gen after the parallel tasks complete
          make proto-gen > /dev/null

          echo "Checking for changes in generated files..."
          if [ -n "$(git status --porcelain ]; then
            echo "Following files are changed..."
            git status

            echo "Changes:"
            git diff

            exit 1
          else
            echo "No changes detected in generated files."
            exit 0
          fi 