name: Check Proto Files Format and Lint

on:
  push:
    branches: [ main, develop, testnet ]
  pull_request:

jobs:
  check-proto-format-lint:
    name: Check Proto Format and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.x'
          cache: true

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.46.0"
          buf_api_token: ${{ secrets.BUF_TOKEN }}

      - name: install deps
        run: buf mod update

      - uses: bufbuild/buf-lint-action@v1

      - name: lint format
        run: buf format -w

      - name: Run proto generation
        uses: ignite/cli/actions/cli@main
        with:
          args: generate proto-go --yes

      - name: Check for changes
        uses: ./.github/actions/check-changes 
