name: Check Proto Files Lint, Format and Generation

on:
  push:
    branches: [ main, develop, testnet ]
  pull_request:

jobs:
  check-proto-lint-format-generation:
    name: Check Proto Lint, Format and Generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.46.0"
          buf_api_token: ${{ secrets.BUF_TOKEN }}

      - name: Proto lint
        uses: bufbuild/buf-lint-action@v1
          with:
            input: proto

      - name: Proto format
        run: buf format -w

      - name: Proto generation
        uses: ignite/cli/actions/cli@main
        with:
          args: generate proto-go --yes

      - name: Check for changes
        uses: ./.github/actions/check-changes 
