name: Check Proto Files Lint, Format and Generation

on:
  push:
    branches: [ main, develop, testnet ]
  pull_request:

jobs:
  check-proto-lint-format-generation:
    name: Check Proto Generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.*'
          cache: true
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.46.0"
          buf_api_token: ${{ secrets.BUF_TOKEN }}
      - name: install deps
        run: buf dep update
      - uses: bufbuild/buf-lint-action@v1
      - name: lint format
        run: buf format -d --exit-code
      - name: Run proto generation
        env:
          DO_NOT_TRACK: 1
        uses: ignite/cli/actions/cli@main
        with:
          args: generate proto-go --yes

      - name: Check for changes
        uses: ./.github/actions/check-changes 
