name: Check Proto Generation Files

on:
  push:
    branches: [ main, develop, testnet ]
  pull_request:

jobs:
  check-proto-gen:
    name: Check Proto Generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.*'
          cache: true

      - name: Run proto generation
        env:
          DO_NOT_TRACK: 1
        uses: ignite/cli/actions/cli@v28.9.0
        with:
          args: generate proto-go --yes

      - name: Check for changes
        uses: ./.github/actions/check-changes 
