name: Check Generated Files

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  check-mock-files:
    name: Check Mock Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check mock files
        run: |
          echo "Running make generate-mocks..."
          make generate-mocks

          echo "Checking for changes in generated files..."
          if [ -n "$(git status --porcelain)" ]; then
            echo "Following files are changed..."
            git status

            echo "Changes:"
            git diff

            exit 1
          else
            echo "No changes detected in generated files."
            exit 0
          fi

  check-proto-files:
    name: Check Proto Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache buf binary
        uses: actions/cache@v3
        id: cache-buf
        with:
          path: /usr/local/bin/buf
          key: ${{ runner.os }}-buf-v1.28.1

      - name: Install buf
        if: steps.cache-buf.outputs.cache-hit != 'true'
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v1.28.1/buf-$(uname -s)-$(uname -m)" -o "/tmp/buf"
          chmod +x "/tmp/buf"
          sudo mv "/tmp/buf" "/usr/local/bin/buf"

      - name: Cache ignite binary
        uses: actions/cache@v3
        id: cache-ignite
        with:
          path: ${{ github.workspace }}/ignite
          key: ${{ runner.os }}-ignite-latest

      - name: Install Ignite
        if: steps.cache-ignite.outputs.cache-hit != 'true'
        run: |
          curl -sSL "https://get.ignite.com/cli" | bash
          echo "${{ github.workspace }}/ignite" >> $GITHUB_PATH

      - name: Check proto files
        run: |
          echo "Running proto format and generation..."
          # Run proto-format and proto-lint in parallel
          make proto-format & make proto-lint & wait
          # Run proto-gen after the parallel tasks complete
          make proto-gen

          echo "Checking for changes in generated files..."
          if [ -n "$(git status --porcelain)" ]; then
            echo "Following files are changed..."
            git status

            echo "Changes:"
            git diff

            exit 1
          else
            echo "No changes detected in generated files."
            exit 0
          fi 