name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  labeler:
    name: 'Labeler'
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v4
      - name: 'Apply Size Labels'
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '10'
          s_label: 'size/S'
          s_max_size: '100'
          m_label: 'size/M'
          m_max_size: '500'
          l_label: 'size/L'
          l_max_size: '1000'
          xl_label: 'size/XL'
          files_to_ignore: "go.mod proto/**/* *.pb.go api/**/*"
