name: Linting

on:
  push:
    branches:
      - master
      - develop
  pull_request:

permissions:
  contents: read

env:
  GO_VERSION: 1.23
  GOLANGCI_LINT_VERSION: v1.61


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

