name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: PR Title Check
        uses: amannn/action-semantic-pull-request@v5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wip: true